### ISSUE TITLE
build doesn't show errors

### ISSUE THREAD

**Issue by yonaskolb** [jakeheis/Ice#11]
Ice version `0.5.0`

`ice build` doesn't show any indication that a build has failed, and just gets stuck

**Comment by jakeheis** [comment]
I'm guessing this was with Swift 4.1? If so, updating to version 0.5.1 (just tagged) should fix it

**Comment by yonaskolb** [comment]
Yep, Swift 4.1
Fixed in 0.5.1, thanks! 👍
