### ISSUE TITLE
Run can't pass along options

### ISSUE THREAD

**Issue by yonaskolb** [jakeheis/Ice#13]
Any options passed through `ice run` aren't recognised by ice
```
ice run tool --version
...
Unrecognized option: --version
```

This is in comparison to swift run which does handle this correctly
```
swift run tool --version
0.1.0
```

This is related to SwiftCLI https://github.com/jakeheis/SwiftCLI/issues/44

**Comment by jakeheis** [comment]
`0.5.5`
