### ISSUE TITLE
Can't add package with branch or commit

### ISSUE THREAD

**Issue by vknabel** [jakeheis/Ice#15]
Hi. First of all: great project!

I just tried to add a dependency which sadly has no versions yet.
The workaround for me was to enter `0` and manually edit the `Package.swift` file.

```bash
$ ice add https://github.com/pointfreeco/swift-overture
Major version: master
Invalid input
Major version: c3082d0c535acd9b6fda9531b54ede37ccbd421d
Invalid input
```

**Comment by jakeheis** [comment]
Thanks for reporting the issue! There definitely should be a way to do this without manually editing the `Package.swift`. I'll try to get around to fixing this issue soon and push out a `0.5.4` release shortly!

**Comment by jakeheis** [comment]
Done in `0.5.6`!

**Comment by vknabel** [comment]
Thank you very much! Will try it out tomorrow.
