### ISSUE TITLE
Doesn’t work with Swift 4.2

### ISSUE THREAD

**Issue by dreymonde** [jakeheis/Ice#23]
When trying to use **Ice** with Swift 4.2 (Xcode 10 beta), 

```
Error: couldn't parse Package.swift
```

always appears.

To reproduce:
1. `echo "4.2" > .swift-version`
2. `ice add jakeheis/SwiftCLI`

Doing some debugging, here’s the actual JSON parsing error when trying to modify **Ice** package itself, for example:

```
keyNotFound(CodingKeys(stringValue: "isTest", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"isTest\", intValue: nil) (\"isTest\").", underlyingError: nil))

Error: couldn't parse Package.swift
```

**Ice** is one of the most useful tools out there, I hope it’ll support Xcode 10 as well ;)

**Comment by jakeheis** [comment]
Swift 4.2 will be supported once #24 is merged in -- I expect to finish Ice 0.7.0 within the next week!

**Comment by dreymonde** [comment]
Awesome! Thanks, I’m so much looking forward to it

**Comment by jakeheis** [comment]
`0.7.0` tagged
