### ISSUE TITLE
Failed to build Ice. Use --verbose to see full output

### ISSUE THREAD

**Issue by PlaceRem** [jakeheis/Ice#25]
Hello. I am trying to install Ice via Mint and get error.

`
🌱 Finding latest version of Ice 
🌱 Resolved latest version of Ice to 0.7.0 
🌱 Cloning https://github.com/jakeheis/Ice.git 0.7.0... 
🌱 Building Ice Package with SPM... 
Failed to build Ice. Use --verbose to see full output
`

When I went to manual mode, I got next error:
`error: cannot load underlying module for 'XCTest' import XCTest ^ error: terminated(1): /Library/Developer/CommandLineTools/usr/bin/swift-build-tool -f /Users/Admin/Ice/.build/release.yaml main output:`

How to avoid error and install Ice?

**Comment by jmmaloney4** [comment]
Had the same issue, I fixed it by selecting a version of command line tools in Xcode Prefrences > Locations > Command Line Tools, there was previously nothing selected there.

**Comment by PlaceRem** [comment]
@jmmaloney4 thanks! it works
