### ISSUE TITLE
Possible iOS/Cocoa Support in the Future?

### ISSUE THREAD

**Issue by markmals** [jakeheis/Ice#31]
Ice looks like an amazing complimentary package manager to the SPM, but it would be even better if developers could use it to build iOS projects as well. Still using SPM as the back-end/infrastructure for Ice, would it be possible to build SPM packages as iOS frameworks and integrate them into an existing app project?

**Comment by Samasaur1** [comment]
Currently, SPM doesn't support iOS or Cocoa apps. Here's what I've been doing: https://stackoverflow.com/questions/44994042/how-to-create-cocoa-gui-application-with-swiftpm/45138790#45138790

Hopefully, this will be added to SPM in the future

**Comment by markmals** [comment]
SPM doesn't *natively* support building products for iOS. But at the end of the day, a Swift package is just some Swift files that get passed to `swiftc` with build settings/flags. It is absolutely possible to pass custom build flags to `swift package` and have it spit out an iOS framework. It's just more work than is worth it for a regular workflow.

However, if there were a build tool that aimed to make doing complicated things fully supported by SPM easier and more accessible to everyone…

**Comment by Samasaur1** [comment]
I believe that SPM can build `.framework`s if you use the correct `.product` in your `Package.swift` file. I was saying that SPM doesn't support the integration with Cocoa apps. I think I misunderstood you
