### ISSUE TITLE
Pass swiftc arguments on build/run commands

### ISSUE THREAD

**Issue by fallback** [jakeheis/Ice#32]
Hi, @jakeheis 

First of all, thanks for the great utility.

I've digged a little through source code and didn't get an ability on how to pass 'swiftc'-related options/arguments like 

`-Xswiftc -static-stdlib -Xswiftc -target -Xswiftc x86_64-apple-macosx10.13`

Is it possible to do so out-of-box or it'll need some pull requests if any?

Thanks.

**Comment by jakeheis** [comment]
I'm afraid this isn't possible at the moment, but it shouldn't be too tough to add this. Are these flags just relevant for `build` and `test`?

**Comment by fallback** [comment]
Thanks for reply. I'm concerned mostly about 'build' action where I'm trying to get single executable binary with the possibility to relocate only this binary to the PATH directory, without preservation of frameworks/dependencies etc relatively to binary.
For example, when I do build with the flags from above, I'm getting this binary and can put it on usb stick/gdrive/dropbox dir without headaches.
However, using documented approaches of Ice's 'build', I have to track all those artifacts (dependencies) produced and have to relocate them accordingly.
Big chances that I'm missing something, though.
Thanks again. I'll take a closer look in sources and provide PR if any. :)

**Comment by jakeheis** [comment]
Done in `0.8.2`!
