### ISSUE TITLE
Getting 'Error: can't parse Package.swift' with Xcode 10.2 installed

### ISSUE THREAD

**Issue by Dschee** [jakeheis/Ice#33]
My open source tool [BartyCrouch](https://github.com/Flinesoft/BartyCrouch) is a package manager tool and I usually update dependencies via `ice update` and then generate the project via `ice xc`. While the first worked after updating to Xcode 10.2 today, the latter gave me this error output:

```bash
Error: can't parse Package.swift
```

When I do `swift package generate-xcodeproj` it works though. I also didn't change my Package.swift file at all before running these commands and it was working before.

**Comment by maximkhatskevich** [comment]
This looks like something about new Swift 5 toolchain. I'm getting errors from SPM which can not resolve dependencies correctly from Package files written in older format. If you install older Xcode version (can be found on dev portal) and set it as version of Xcode used for command line - then all issues should go away.

**Comment by jakeheis** [comment]
This should be fixed in `0.8.0` which adds support for Swift 5. Feel free to reopen if any issues are still present!

**Comment by maximkhatskevich** [comment]
Thanks a lot! I'll give it a try and let you know if any issues come up.

**Comment by maximkhatskevich** [comment]
The error about parsing seems to be gone, but now I'm getting other error (see screenshot attached).
<img width="526" alt="Screen Shot 2019-06-17 at 5 02 32 PM" src="https://user-images.githubusercontent.com/2624646/59614945-ff9df100-9121-11e9-931a-aea31c09b0b8.png">

**Comment by Dschee** [comment]
I don't mean to be rude in any way, but I want to note that my main takeaway from this is that support for new Swift versions can take up to 3 months, in other words: I shouldn't get used to Ice. Too bad ...

**Comment by jakeheis** [comment]
That's very rude and completely unnecessary. I'm a full time student maintaining this for others for free. To complain that someone else isn't updating a tool for you fast enough is petulant and ridiculous. If you want it updated faster, either contribute or find a tool you can pay for where it's actually reasonable to expect quick updates.

**Comment by jakeheis** [comment]
@maximkhatskevich I appreciate the issue report, I haven't seen that issue before but I'll certainly look into it when I have time

**Comment by Dschee** [comment]
I really didn't mean to be rude and I can totally understand that you might not be able to update everything as quickly as some people might hope for. What I personally hoped for was, that you were using your tool on a daily basis yourself and therefore would have needed to update it to the latest Swift versions with intrinsic motivation. That's true for tools _I_ build which is probably why I assumed the same for this tool. But I didn't know that you were a student, so again, I'm not blaming you. Actually, I'm pretty impressed now that you have made so many contributions to the community without even needing all that stuff in your daily job, so kudos to you.

Having that said, for an infrastructural tool like a package manager it is very important to be kept up-to-date for people to be able to actually trust in it. Additionally, package managers are usually not the most trivial piece of software, so contributing isn't that easy, too. In my statement above, I merely tried to express guidance for anyone with hopes like me, that it might not be a good idea to rely on this tool since 3 months is a pretty long time if you need something to always work. I didn't mean to say "hey, it's your fault, hurry up next time!" (it's not your fault, I appreciate the work you've done) – it was more to say "hey guys, I noticed that there isn't enough interest by the collaborators and users of this tool to stay up-to-date right now, so don't expect it to always work for you".

I'm sorry if you didn't want to hear that, but that's the truth for the business side of things. Also, telling me that I should "find a tool (I) can pay for" could also be considered rude, given that there is not even such an option. Neither is there a payment option for this project, nor is there another such project to go to. The closest thing may be [Accio](https://github.com/JamitLabs/Accio), which I contributed to the community, being aware that it brings some responsibility with it regarding all its users who rely on it.

I also consider telling you that fast(er) updates for a package manager is necessary an important kind of feedback. It is you who decided that it was just a "completely unnecessary" complaint. I think our problem is just a misunderstanding. To explain it with the [four ears model](https://en.wikipedia.org/wiki/Four-sides_model), what I (as the sender) intended to communicate was on the factual and self-revealing level, what you (as the receiver) understood was mainly on the appeal and maybe the relationship level. At least that's my best guess.

**Comment by maximkhatskevich** [comment]
@jakeheis please ignore people like @Dschee, he probably forgot his good manners at home today when went online. Thank you very much for this nice tool @jakeheis, I especially appreciate you keep it as simple wrapper and maintain 100% compatibility with standard Swift Package Manager, so I can easily switch back and forth if I need/want to.

**Comment by maximkhatskevich** [comment]
@Dschee please consider to hold on with comments/feedback like this. This is inappropriate place for that kind of feedback, especially since nobody asked for this. This is comments section on particular issue, anything unrelated to this particular issue should be considered off topic. So you are starting inappropriate conversation (it's an open source software, use it as is or not use - it's up to you, why would you have any expectations at all?) in an inappropriate place (it's not a forum for user/customer feedback, really). So let's end this right here right now, nobody will maintain any hard feelings towards you, we can consider this as little misunderstanding. Peace!

**Comment by Dschee** [comment]
Okay ... if you say so. Then I will just shut up from now on.
Sorry for sharing my thoughts in the first place.
