### ISSUE TITLE
Failed to install Ice on MacOS Catalina running Xcode 11.3

### ISSUE THREAD

**Issue by 3141592653589793238462643383279502865** [jakeheis/Ice#37]
st0rm@equin0xs-MacBook-Pro Ice % mint install jakeheis/Ice
🌱  Finding latest version of Ice
🌱  Cloning Ice 0.8.1
🌱  Resolving package
🌱  Building package
[1/5] Compiling Rainbow BackgroundColor.swift
[2/5] Compiling PathKit PathKit.swift
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/.build/checkouts/PathKit/Sources/PathKit.swift:98:14: warning: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'Path' to 'Hashable' by implementing 'hash(into:)' instead
  public var hashValue: Int {
             ^
[3/6] Compiling SwiftyTextTable TextTable.swift
[4/6] Compiling SwiftCLI ArgumentList.swift
[5/7] Compiling Icebox Icebox.swift
[6/8] Compiling TestingUtilities TestingUtilities.swift
[7/8] Compiling IceKit Config.swift
[8/9] Compiling IceCLI Add.swift
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:26:6: error: cannot convert value of type 'Key<_>' to specified type 'Version'
    @Key("-f", "--from", description: "The minimum version of the dependency to depend on; allows more recent versions")
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:29:6: error: cannot convert value of type 'Key<_>' to specified type 'Version'
    @Key("-e", "--exact", description: "The exact version of the dependency to depend on")
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:32:6: error: cannot convert value of type 'Key<_>' to specified type 'String'
    @Key("-b", "--branch", description: "The branch of the dependency to depend on")
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:35:6: error: cannot convert value of type 'Key<_>' to specified type 'String'
    @Key("-s", "--sha", description: "The commit hash of the dependency to depend on")
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:42:28: error: use of unresolved identifier '$from'
        return [.atMostOne($from, $exact, $branch, $sha, $local)]
                           ^~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:42:35: error: use of unresolved identifier '$exact'
        return [.atMostOne($from, $exact, $branch, $sha, $local)]
                                  ^~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:42:43: error: use of unresolved identifier '$branch'
        return [.atMostOne($from, $exact, $branch, $sha, $local)]
                                          ^~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:42:52: error: use of unresolved identifier '$sha'
        return [.atMostOne($from, $exact, $branch, $sha, $local)]
                                                   ^~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:53:12: error: initializer for conditional binding must have Optional type, not 'Version'
        if let version = from {
           ^
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:55:19: error: initializer for conditional binding must have Optional type, not 'Version'
        } else if let exact = exact {
                  ^
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:57:19: error: initializer for conditional binding must have Optional type, not 'String'
        } else if let branch = branch {
                  ^
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Add.swift:59:19: error: initializer for conditional binding must have Optional type, not 'String'
        } else if let sha = sha {
                  ^
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Build.swift:16:6: error: cannot convert value of type 'Key<_>' to specified type 'String'
    @Key("-t", "--target", description: "The individual target to build; cannot be used with --product")
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Build.swift:19:6: error: cannot convert value of type 'Key<_>' to specified type 'String'
    @Key("-p", "--product", description: "The individual product to build; cannot be used with --target")
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Build.swift:32:28: error: use of unresolved identifier '$target'
        return [.atMostOne($target, $product)]
                           ^~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Build.swift:32:37: error: use of unresolved identifier '$product'
        return [.atMostOne($target, $product)]
                                    ^~~~~~~~
/private/var/folders/v3/rmyggr5x7vlbl100t1spwzl40000gn/T/mint/github.com_jakeheis_Ice/Sources/IceCLI/Commands/Build.swift:56:52: error: cannot convert value of type '[_.Element]' to expected argument type 'SPM.BuildOption??'
        let buildOption: SPM.BuildOption? = target.flatMap { .target($0) } ?? product.flatMap { .product($0) }
                                            ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
🌱  Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.15". Use --verbose to see full output
🌱  Failed to build Ice 0.8.1 with SPM


Complete noob to MacOS, Swift and Xcode. Any help at all would be greatly appreciated. :)

(P.S. Sorry if this is a duplicate lol)

**Comment by jakeheis** [comment]
Just pushed `0.8.2`, could you try installing that? I believe it should have fixed the problem

**Comment by 3141592653589793238462643383279502865** [comment]
> Just pushed `0.8.2`, could you try installing that? I believe it should have fixed the problem

Worked! Thank you so much! :)
